name: course4
channels:
  - conda-forge
dependencies:
  - cmasher
  - jupyter
  - pandas
  - pillow
  - pyarrow
  - requests
  - scipy
  - seaborn
  - sphinx
  - sphinx-gallery
  - sphinx_rtd_theme
  - sphinx-togglebutton
  - matplotlib
  - numpy
  - scikit-learn
  - linkify-it-py
  - pip
  - xgboost
  - pyreadstat
  - termcolor
  - time
  - pip:
      - setuptools
      - lxml
      - adjustText
      - highlight-text
      - kloppy
      - mplsoccer
      - sphinxcontrib-youtube
      - myst-parser
      - ffmpeg


#    - pyobjc-core=10.2
#  - pyobjc-framework-cocoa=10.2
#  - libgfortran=5.0.0